//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIAPP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO2
    {
        public long Usuario2ID { get; set; }
        public string Usuario2Nick { get; set; }
        public string Usuario2Pass { get; set; }
        public string Usuario2Tipo { get; set; }
        public string Usuario2Estado { get; set; }
        public string Usuario2Fecha { get; set; }
        public string Usuario2Status { get; set; }
    }
}
