//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIAPP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public long UsuarioID { get; set; }
        public string UsuarioNick { get; set; }
        public string UsuarioPass { get; set; }
        public string UsuarioTipo { get; set; }
        public string UsuarioEstado { get; set; }
    }
}
